var app = angular.module('app', []);
app.controller('ctrl', ['$scope', function ($scope) {

    $scope.numbers = [
        [
       [
           [null,5,null],
           [null,7,null],
           [null,null,null]
       ],
         [
           [null,9,null],
           [null,4,null],
           [2,8,null]
       ],
         [
           [null,null,1],
           [null,null,null],
           [9,null,null]
       ],
        ],
           [
       [
           [null,null,null],
           [null,null,3],
           [null,null,null]
       ],
         [
           [null,null,null],
           [null,null,5],
           [null,null,null]
       ],
         [
           [null,null,null],
           [null,null,6],
           [null,8,null]
       ],
        ],
           [
       [
           [null,null,null],
           [null,null,2],
           [null,null,8]
       ],
         [
           [null,null,7],
           [null,null,null],
           [null,null,null]
       ],
         [
           [5,null,null],
           [null,null,null],
           [null,4,null]
       ],
        ]
    ];
}]);